### ISSUE TITLE
Fix IbScape Menu positioning problems

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/ibgib#106]
It is becoming mildly annoying that the bubble no longer positions itself correctly!

**Comment by rob3c** [comment]
Maybe this is a CSS difference between browsers?

**Comment by bill-mybiz** [comment]
Ah I haven't even checked on Firefox...that would be a good thing to check.

**Comment by bill-mybiz** [comment]
It still works incorrectly on firefox. This did however make me realize that I didn't say which "bubble" I was referring to...I am actually talking about the popup menu that is another d3 force layout. In refactoring it out in the `IbScape` JS class, I apparently changed how the positioning works and now it's often off to the right side of the screen.

I'm going to adjust the name of this issue to better reflect the problem! :slightly_smiling_face:

**Comment by bill-mybiz** [comment]
This is resolved in the current approach in #15 Live Interaction issue. The overlayed ibScape menu always appears in the middle of the screen now to reduce complexity. It also is much reduced in importance/frequency, since there are "quick commands" that appear when you click individual nodes.

So for now, I'm closing this and will reopen if this "becomes an issue" again.
