### ISSUE TITLE
haikuGib

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/ibgib#108]
ibGib. ib. Gib. ib.
Gib ibGib ib. Gib ib. Gib.
ib. Gib. ib. Gib ib.

**Comment by bill-mybiz** [comment]
https://www.ibgib.com/ibgib/HaikuGib^E6B1D73F6EC13F924F12EC292296E3054450CFF3956BBBA664C950F106984D5A

**Comment by rob3c** [comment]
Lol reminds me a bit of the (infamous Buffalo sentence)[https://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo]
