### ISSUE TITLE
Explore Bucklescript TEA for front end

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/ibgib#178]
I want to explore creating _an additional_ front end in parallel to the current one. I'm not quite sure how I should go about doing this with regards to adding something to `web_gib` or if I should be creating an additional phoenix application or what.

This may be a slow progression, so I'm probably going to want to create an additional long-running issue branch and rebase master back into as needed.

### TEA on github

https://github.com/OvermindDL1/bucklescript-tea

### Bucklescript main threads on EF

https://elixirforum.com/t/bucklescript/1579
https://elixirforum.com/t/why-bucklescript/2319

### Bucklescript examples

https://github.com/OvermindDL1/bucklescript-tea#usage

https://github.com/OvermindDL1/bucklescript-testing

**Comment by bill-mybiz** [comment]
This may actually be a front end that is not as note-keeping-ish, and rather more of a technical front end with a different aim. This could be to explore things like creating data "class" structures or "types", instantiating them, etc.

I think I would want to share authorization, so I'll probably have to pull more of that out from the existing `web_gib`. How much so will depend on exactly what I need to do to get this going, via either the existing phoenix app or a new one.

**Comment by OvermindDL1** [comment]
Strong-typing is indeed awesome.  ^.^

Of course if you need anything, @ ping me.  :-)

**Comment by bill-mybiz** [comment]
Thanks @OvermindDL1 ! :smiley: 

###### _(I'm definitely going to take you up on that :wink:)_

In addition to the awesome prospect of returning to strong-typing, I'm ultimately looking for something that is react-like, lean, fast, and functional. As it stands, React/Elm/others don't resonate with me for sundry reasons. I'm a big fan of KISS and from what I've seen so far, TEA looks really promising.

I'm going to have to "buckle down" (ouch :face_with_head_bandage:)  and do some experimenting first, and by then I'm sure I'll have a question or two hehe.

**Comment by bill-mybiz** [comment]
OCaml ibGib: https://www.ibgib.com/ibgib/OCaml%5E8EF13CD82333C37A904A8DD91A88E7E0585EE1DF83C7DD978DAAEDF756DAB0C5

Will make rel8d ibGib for Bucklescript and TEA when I get to them.

**Comment by OvermindDL1** [comment]
Hah, that is cool.  ^.^

**Comment by bill-mybiz** [comment]
Glad you dig it... It's only the beginning, one teeny tiny use case! :smiley:

**Comment by bill-mybiz** [comment]
(btw if you double click any node, it will automatically unfold..."source" nodes are duplicated for convenience.)

**Comment by OvermindDL1** [comment]
> (btw if you double click any node, it will automatically unfold..."source" nodes are duplicated for convenience.)

Heh, already noticed.  ^.^

**Comment by bill-mybiz** [comment]
I'll mark that up as a win for the UX so far! hehe 

Also you can comment/add URL link(s), but pic/image requires "logging in" with an email address. I am in the process of implementing notifications ( #175 , #166, #173 ), since my girlfriend and I are dogfooding it and we basically respond to each other then ping an instant message that we did so. 

In the long run, this web app could be redone in a react-style Bucklescript, since it is highly functional and highly reactive (hence this github issue). I initially looked at Elm and React and others, but I just was already swamped with technologies from Elixir/Erlang and went with plain JS and d3 (which has been amazingly powerful actually). But I want to diversify a little bit on the consumption of the engine, so that's why I'm want to start a different app with Bucklescript first. 

OCaml is looking very promising so far and I hope to get to Bucklescript/TEA :soon:!

**Comment by ChipNowacek** [comment]
As a data modeling/ontology guy, just imagine if the database connection was fast enough that you could expose the model directly instead of having to do some form of what is essentially replication in React/Reagent etc. That's why I arrived at just straight JS/d3. I looked long and hard at straight Reagent and then Keechma (and some Re-Frame). For my work, I essentially need direct access to the database with (initially) very little middleware or data replication beyond what d3 needs immediately.

That's my current understanding of my situation anyway.

**Comment by OvermindDL1** [comment]
@ChipNowacek That is something GraphQL is really for, and Elixir has Absinthe to expose GraphQL out, and there is an absinthe phoenix project to access GraphQL blazing fast over the phoenix websockets, thus...  ^.^

**Comment by bill-mybiz** [comment]
@ChipNowacek ibGib is largely about collaboration and unification of data silos. So if you want the benefits of open collaboration of your data, with full history of all changes of the data throughout the lifetime of collaboration, then I'd say keep going with ibGib...I certainly love talking about the ontological aspects!

@OvermindDL1 I'm still considering Bucklescript for similar reasons to @ChipNowacek, of trying to minimize the middle layer, but I'm waiting a bit to see how they resolve the async/promise issues. Also I'm doing some other stuff as well of course! :laughing:

**Comment by ChipNowacek** [comment]
@OvermindDL1 Thank you. I do have access to a TinkerPop3 interface on my backend though I haven't set it up. I'm SPARQL via HTTP for now.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I'm still considering Bucklescript for similar reasons to @ChipNowacek, of trying to minimize the middle layer, but I'm waiting a bit to see how they resolve the async/promise issues. Also I'm doing some other stuff as well of course! 😆

@bill-mybiz  There is the standard functional way of those, however they are currently PR'ing in wrappers to use javascript native promises/async too, so very soon.  :-)

Regardless, if using bucklescript-tea or something similar, there are no promises/async issues as the design is entirely async.

> @OvermindDL1 Thank you. I do have access to a TinkerPop3 interface on my backend though I haven't set it up. I'm SPARQL via HTTP for now.

@ChipNowacek You really should take a look at GraphQL, it is becoming very big due to Facebook pushing it out on everyone.  ^.^

**Comment by ChipNowacek** [comment]
@OvermindDL1 I know you speak the truth. I'll go see what it takes to get that interface working.

**Comment by ChipNowacek** [comment]
Since what middleware (really admin-script-ware) I have is Clojure, this is an interesting announcement: [Open Sourcing Lacinia, our GraphQL Library for Clojure](https://medium.com/walmartlabs/open-sourcing-lacinia-our-graphql-library-for-clojure-96a4ce5fc7b8). I'd be looking into Elixir except I'm dependent on a Clojure-based library for now. I have a lot of respect for the Elixir folks I've run into.

**Comment by bill-mybiz** [comment]
> There is the standard functional way of those, however they are currently PR'ing in wrappers to use javascript native promises/async too, so very soon. :-)

> Regardless, if using bucklescript-tea or something similar, there are no promises/async issues as the design is entirely async.

Ah, that is what I had initially thought, but I still don't understand how it works. With Erlang/Elixir, I understand because of the BEAM. It is essentially its own super implementation of a nodal, pre-emptive operating system, with each node in actor parlance being an Actor with message boxes. But more functionally, I see these nodes as functions and the message box is basically a queuing system for passing arguments to it in a completely parallel manner. That I understand.

But I don't understand how OCaml is also "async"? :confused: Does it also have a scheduling system that divvies out processing resources to any concurrently operating threads? 

For example, [here](https://news.ycombinator.com/item?id=12403723) is a comment from almost a year ago talking about the lack of async in Bucklescript vs other ocaml js libs. When I google "Bucklescript async", I get the github thread (which I won't link to in order to avoid spamming their threads hah) about including the native promises and async.

I've already gone down the road of ubiquitous rxjs, but I wasn't a fan of how fractured the landscape was with v5 vs v4, as I was using v5 and there were just heaps of problems. That's why I went to the BEAM in the first place! :smiley:

I'm sure I need to just bite the bullet and start doing some darn concept projects, but it's hard to jump in when I don't have a clear idea about the async aspect. But that's what the starting projects would be for... :exclamation:

**Comment by OvermindDL1** [comment]
Bucklescript does async like javascript does, since it just compiles down to javascript.  ^.^

Bucklescript-tea is just Elm in Ocaml/Bucklescript/Reason/Etc...  So it does async via message passing, everything is a message to your main update.

**Comment by bill-mybiz** [comment]
> Bucklescript does async like javascript does, since it just compiles down to javascript. ^.^

cheeky... hrmm.. (yes, I already figured that part out... :laughing:)

> Bucklescript-tea is just Elm in Ocaml/Bucklescript/Reason/Etc... So it does async via message passing, everything is a message to your main update.

I'm still thinking about the case of firing off an async process from within an OO paradigm, but this is probably covered in the more functional architecture. I probably just need to do the beginner apps, as I said. I went down that road a little with Elm, but that was curtailed by some not too friendly interactions with their slack channel. Thanks for your input as always @OvermindDL1 :smile:

**Comment by OvermindDL1** [comment]
> I'm still thinking about the case of firing off an async process from within an OO paradigm, but this is probably covered in the more functional architecture. I probably just need to do the beginner apps, as I said. I went down that road a little with Elm, but that was curtailed by some not too friendly interactions with their slack channel. Thanks for your input as always @OvermindDL1 😄

Yeah, that are oddly not a very pleasant group to be around...  :-/

Yeah the OO and functional styles are very different, and the elm/tea style is very event driven, there is no firing off async processes in javascript, the best you can get are workers, but they can only communicate via messages to/from the main window script too, so event driven is how javascript in browsers works so it is the method to follow.  ^.^
