### ISSUE TITLE
Revamp web app

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/ibgib#205]
Time to rearchitect from the ground up-ish. I did the initial web_gib web app purposefully without any real structure to it because I was learning so many different things at the same time, all while trying to figure out ibGib's current incarnation itself. Now that I have a handle, it is time to abstract away the d3 stuff from the ibGib stuff and get a better overall UX going.

I've looked over Bucklescript per #178 , but I've decided to go with TypeScript. I love all the work @OvermindDL1 has put into TEA especially, and I enjoyed going through the tutorials. But in the end it was the licensing complications that arise. I eschew the tit-for-tat licensing legal issue, and it was just too complicated. (MIT is even too much, but meh, I digress.)

So, viz revamping, I'm abstracting things into interfaces/types/etc., to get it more generalized. I have an approach and a vision to have feasible implementations of multiple renderings for ibGib now.

This is to include the following, _as context renderers(!)_:

* Todo
  * Visual (pic), Comment, link, generic ibGib
* Chat
  * Focuses on N users (chatters) similar to group messaging with SMS or other chat apps.
* Blog
  * Focuses on 1 user (writer), with a layout that organizes by time/topic.
* Files/Folders Explorer
  * Focuses on power users
  * I should be able to use Vim in browsers again with ibGib!
    * _(Lost this capability when FF broke Vimperator)_
  * Unifies the concept of a file & folder, ibGib-style.
* Existing d3 IbScape.
  * Should be backwards compatible with the existing IbScape UX.

I am excited about the context renderer aspect, because each of these are projections of the ibGib. You should be able to view your "chat" as if it were a blog (no idea how good of an idea that will be though. Possibly more useful is to view your chat as a todo. It should be able to have auto-updates on query ibGib, i.e. a "live" query. Meh, lots of interesting things of course. But for now, the goal is to abstract things away and improve the actual architecture of the current front end.

This will also address the Whys, Wherefores and Website stuff in issue #118. It will be much more obvious the utility of the site, as the UX I have in mind is much more intuitive and straight-forward. The d3 interface is interesting and fun, but it's too broad and clunky.

**Comment by OvermindDL1** [comment]
> MIT is even too much, but meh, I digress.

So a license that basically says to do whatever you want as long as you do not make changes to it and claim they are my changes instead of your own?  ;-)

It is one of the most friendly business licenses out, other than DWTFYW license I guess.  ^.^

I can always add another license too if you want, I just used the default one from OCaml itself considering how heavily used it it.  :-)

_/me has yet to get Typescript working well on windows..._

**Comment by OvermindDL1** [comment]
Hmm, also Typescript is apache licensed:  https://github.com/Microsoft/TypeScript/blob/master/LICENSE.txt
The apache license is *more* restrictive than the MIT license, so I'm doubly confused here?  O.o?

Plus neither license effects the code you right, only if you edit the original ocaml or typescript code, so, I'm confused?

**Comment by bill-mybiz** [comment]
> The apache license is more restrictive than the MIT license, so I'm doubly confused here? O.o?

I was just saying that _even_ the MIT (which is the least restrictive without getting into strange "Unlicensed" philosophical/logical conundrums) is too restrictive. I'm maybe too much of an idealist, but since I don't figure I'll be producing anything for others to consume anytime soon, it shouldn't be a big deal.

The licensing to which I was referring was the (L)GPL stuff. It took me awhile to accept that Apache 2 is _somewhat_ compatible with MIT (I almost didn't use Elixir because of it). But both GPL and LGPL just make my brain melt. Programming ibGib is hard enough without the added complications. 

But that was just the proverbial straw and caml. Really I'm just feeling a bit overwhelmed. I'm extremely adept at OOP, I got TS + webpack going, and it is simply easier for the short term to use an established methodology. (I'm a slow learner nowadays that I'm older and the brain doesn't work as well as it used to.) Looking into what I need the update structure to be though certainly makes me foresee reproducing (probably poorly) existing paradigms e.g. Angular/React event propagation, which is why TEA is so appealing. And I have tried Angular (which is basically a TS framework) and I'm not a fan of the limitations of dynamically composing components. Of course, that was when they were still in the permanent flux of v2 betas, but from what I've seen recently I still don't like it. And I simply don't like React - the syntax, the design decisions, and how incredibly non-lightweight it is.

> Plus neither license effects the code you right, only if you edit the original ocaml or typescript code, so, I'm confused?

If I go with BS, then I would most likely want to contribute to TEA (e.g. for warnings), and that is where the licensing affects me. 

Probably just overwhelmed. I've been working on this thing for so long! :laughing: 
And I'm excited about the layout I have in mind for ibGib's multi-rendering look. But I'm running out of juice...it's like a marathon runner co-worker of mine used to say: People at the 25 mile marker are yelling "just one more mile", but it's a looong mile. hah

**Comment by OvermindDL1** [comment]
>  But both GPL and LGPL just make my brain melt. Programming ibGib is hard enough without the added complications.

Hehe, GPL I quite dislike, it is very... virus'y.  LGPL is basically GPL constrained to inside the library it is assigned to, so if you Edit the source of that library then you must release the source back out (helps keep bug fixes upstream), but it does not infect anything that uses it.

If you want to try something more javascript'y but still functional I'd recommend looking at purescript then, it is like typescript but functional, similar tooling too.  It has a TEA-like library as well though I do not recall the name of it.  It takes a while to compile though like Elm does (they are both Haskell'y in that way), but very powerful.  :-)

> If I go with BS, then I would most likely want to contribute to TEA (e.g. for warnings), and that is where the licensing affects me.

Contributing is fine, it is highly in flux and there have been others contributing too.  The only thing that license means for you contributing is that the source you submit in you must allow me to license it as LGPL is well and that anyone who edits the source you put in has to do the same, it just means it will stay open.  :-)

But no worry, LGPL does not infect 'your' code of your projects, the GPL sucks in that way...

> Probably just overwhelmed. I've been working on this thing for so long! 😆
> And I'm excited about the layout I have in mind for ibGib's multi-rendering look. But I'm running out of juice...it's like a marathon runner co-worker of mine used to say: People at the 25 mile marker are yelling "just one more mile", but it's a looong mile. hah

Entirely hear that!  I have so many projects across work and real-life both that it is indeed quite overwhelming.  ^.^;

**Comment by bill-mybiz** [comment]
> If you want to try something more javascript'y but still functional I'd recommend looking at purescript then, it is like typescript but functional, similar tooling too.

I actually am liking the OCaml syntax from what I've read/done so far, and I like what I've seen about what you've done with TEA. (I also am appreciating the power of the dynamic composition afforded with modules as opposed to OO-inheritance + generics, btw...it's pretty sweet.)  But what I _really_ like (and what put me over the top to go ahead and start on the concept apps) is the care and effort you put into the overbots blog posts. They're very good walkthroughs - which is not remotely easy - and they're right at my level. It shows that you're committed, competent, and you've already proven yourself accessible.  The advantage of TEA over TS largely hinged on the love you've shown for BS, TEA, and OCaml. 

But...

> LGPL is basically GPL constrained to inside the library it is assigned to, so if you Edit the source of that library then you must release the source back out (helps keep bug fixes upstream), but it does not infect anything that uses it.

> But no worry, LGPL does not infect 'your' code of your projects,

I'm just not sure of this at all. I've now re-skimmed [GPL 3](https://github.com/bloomberg/bucklescript/blob/master/COPYING), read all of [LGPL 3](https://github.com/bloomberg/bucklescript/blob/master/COPYING.LESSER) and [Bucklescript license](https://github.com/bloomberg/bucklescript/blob/master/LICENSE), as well as the relevant large chunks of the [Apache 2](https://github.com/Microsoft/TypeScript/blob/master/LICENSE.txt) for giggles. It is nowhere clear to me that it isn't infected, since the LGPL, in addition to being a big legal document itself, is actually a patch to the original GPL, with the Bucklescript license tacked on the top (albeit thankfully small enough to ingest without too much pain). If I were a large company with a team of lawyers, this wouldn't really phase me. 

But I'm a debilitated solo dude that just wants to writes the codes and the licensing is just too ambiguous for me. :slightly_frowning_face: I'm probably just getting old...

But the up-side is you're not really losing anything in the bargain since I don't have a user base or product! :laughing: 

I think I'll still complete the overbots walkthroughs for the fun of it though. Maybe I can incorporate it in the future with something, especially if they ever change the license to be more permissive. After all, my goal is to open up ibGib to work implemented in any language with distributed nodes. The ibGib data model by itself is essentially a DTO/struct/shape that defines a message structure passed among actor nodes. This distributed nodal goal is how I came to Erlang (and then Elixir) in the first place!

**Comment by OvermindDL1** [comment]
> I actually am liking the OCaml syntax from what I've read/done so far, and I like what I've seen about what you've done with TEA. (I also am appreciating the power of the dynamic composition afforded with modules as opposed to OO-inheritance + generics, btw...it's pretty sweet.) But what I really like (and what put me over the top to go ahead and start on the concept apps) is the care and effort you put into the overbots blog posts. They're very good walkthroughs - which is not remotely easy - and they're right at my level. It shows that you're committed, competent, and you've already proven yourself accessible. The advantage of TEA over TS largely hinged on the love you've shown for BS, TEA, and OCaml.

In my opinion, OCaml has one of the best type systems out.  The only real big thing I want added to it is Implicit Modules, which looks to come in someday.  ^.^

I plan more of those posts as well, just have to find the time for it, probably next week.  :-)

> I'm just not sure of this at all. I've now re-skimmed GPL 3, read all of LGPL 3 and Bucklescript license, as well as the relevant large chunks of the Apache 2 for giggles. It is nowhere clear to me that it isn't infected, since the LGPL, in addition to being a big legal document itself, is actually a patch to the original GPL, with the Bucklescript license tacked on the top (albeit thankfully small enough to ingest without too much pain). If I were a large company with a team of lawyers, this wouldn't really phase me.

As long as you do not intend to package up a custom version of bucklescript-tea then it does not touch you at all.  ;-)
Plus I'd want you to commit changes back, that is how it grows!  :-)

> But I'm a debilitated solo dude that just wants to writes the codes and the licensing is just too ambiguous for me. 🙁 I'm probably just getting old...

* In essence, if you want to use a library and not edit it to make custom versions (calling in to it is fine) then LGPL is fine.  It does not touch the code that uses it, calls in to it, or anything else of the sort.  It only means that modifications to the library itself must be released back out, but any code that calls 'in' to it is exempt regardless.
* GPL is infectious, I highly recommend always staying clear of it.
* MIT/Apache/BSD/DWTFPL/etc... are all fine, you can even edit them and release custom versions of the libraries and all.

> But the up-side is you're not really losing anything in the bargain since I don't have a user base or product! 😆

Would not touch me in any case.  Plus more people using bucklescript-tea means more eyes viewing it to add features, fix bugs, etc...  :-)

> I think I'll still complete the overbots walkthroughs for the fun of it though. Maybe I can incorporate it in the future with something, especially if they ever change the license to be more permissive. After all, my goal is to open up ibGib to work implemented in any language with distributed nodes. The ibGib data model by itself is essentially a DTO/struct/shape that defines a message structure passed among actor nodes. This distributed nodal goal is how I came to Erlang (and then Elixir) in the first place!

You will find a lot of libraries, and indeed a lot of languages use LGPL.  As stated, the only time it matters to you is if you released a closed-source edited version of the library.  Releasing a closed-source non-edited version of the library is still fine regardless.  ^.^
