### ISSUE TITLE
Umbrella mix test deadlock and Minimal setup to get get up and running to run tests

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/ibgib#208]
https://elixirforum.com/t/mix-test-fails-in-umbrella-ecto-phoenix-db-couldnt-be-dropped/1280/6

Tomasz (Eiji on EF) is being nice enough to try to help me troubleshoot why the tests hang when run from the root of the umbrella app. But he's having difficulty getting up and running, so I'm going ahead and making an issue here for future reference.

**Comment by Eiji7** [comment]
Hi, @bill-mybiz: is I posted in forum: sorry about delay and I have a question:
Is it possible to run tests without docker now? I will setup docker, but this will take me some time and I through that it's possible to at least run tests without it and check what tests will fail or not for me.

**Comment by bill-mybiz** [comment]
@Eiji7 Howdy :wave:

I would think if you have postgres setup locally on your machine that you could simply point to your localhost and run it. You would still have to do the steps as I have in the README for `mix ecto.create/migrate`. I don't _think_ Docker is what is causing it to hang.

**Comment by Eiji7** [comment]
@bill-mybiz: ok, here is what I have:

1. I downloaded this repo from git default branch
2. Using Atom editor I commented line that import `dev.secrets.exs`, commented database hostname and port parts and added `hostname: "localhost"` for `:web_gib WebGib.Data.Repo` (I have same configuration in other projects of course except database name)
2. I entered directory: `ibgib/ib_gib_umb`
3. I executed `mix deps.get`
4. I executed `mix deps.compile`
5. I executed `mix ecto.create`

After compile deps I got this error message:
```elixir
14:46:54.522 [error] GenServer #PID<0.5181.0> terminating
** (DBConnection.ConnectionError) tcp connect: network is unreachable - :enetunreach
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for IbGib.Data.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect: network is unreachable - :enetunreach
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

7. I executed: `mix deps.update --all`
8. I executed: `mix deps.compile`
9. I executed: `mix ecto.create`

after compile new versions of dependencies I got:
```elixir
** (UndefinedFunctionError) function Ecto.Repo.Supervisor.config/3 is undefined or private
    Ecto.Repo.Supervisor.config(IbGib.Data.Repo, :ib_gib, [])
    lib/mix/tasks/ecto.create.ex:36: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/project.ex:313: Mix.Project.in_project/4
    (elixir) lib/file.ex:1162: File.cd!/2
    (mix) lib/mix/task.ex:394: anonymous fn/4 in Mix.Task.recur/1
```

Please let me know if I have missed something.

**Comment by bill-mybiz** [comment]
> Using Atom editor I commented line that import dev.secrets.exs, commented database hostname and port parts and added hostname: "localhost" for :web_gib WebGib.Data.Repo (I have same configuration in other projects of course except database name)

I'm thinking that you need to leave the port number in there, per the config at https://github.com/elixir-ecto/ecto. They are using localhost and they still have the port number. This is what the DBConnection error is saying, that it can't even establish a connection to postgres (this is via postgrex, as [they use dbconnection](https://github.com/elixir-ecto/postgrex/blob/master/mix.lock) to connect). This means that nothing after this connection even comes into play. So if you add the port back in there and use localhost (just like it shows at the aforementioned official ecto repo), see if that gets you past the error.

> after compile new versions of dependencies I got:

I would roll back those updates, as this seems to have introduced a new configuration error that probably is because of some breaking change somewhere along the way. I definitely need to update all of my dependencies anyway, but at this point that would just add unnecessary complexity for you. The elixir lock file does a great job for dependencies AFAICT. I believe you would just reset the lock file to its previous state, then do some `mix deps.clean`, `mix deps.get` etc., but maybe you would know this better than I.

In the meantime, I can try to install postgres directly on my other machine and see if I can reproduce a localhost configuration.

**Comment by Eiji7** [comment]
@bill-mybiz
> I'm thinking that you need to leave the port number in there, per the config at https://github.com/elixir-ecto/ecto. They are using localhost and they still have the port number. This is what the DBConnection error is saying, that it can't even establish a connection to postgres (this is via postgrex, as they use dbconnection to connect). This means that nothing after this connection even comes into play. So if you add the port back in there and use localhost (just like it shows at the aforementioned official ecto repo), see if that gets you past the error.

Nope, as I said except database name I have exactly same configuration for that database. In other projects that I have on my hardware it's working. Of course I tried it and I got same error.

**Comment by bill-mybiz** [comment]
> Using Atom editor I commented line that import dev.secrets.exs, commented database hostname and port parts and added hostname: "localhost" for :web_gib WebGib.Data.Repo (I have same configuration in other projects of course except database name)

When you said about the other projects, I thought you were referring to the `ib_gib` "project" - which of course isn't a project, rather an application in Elixir jargon. My bad! You mention you changed `WebGib.Data.Repo` config - did you change the configuration for the `IbGib.Data.Repo` as well? The exact error you copied was `The database for IbGib.Data.Repo couldn't be created:`, which is referring to the `ib_gib` repo.

> 3. I entered directory: ibgib/ib_gib_umb
> 4. I executed mix deps.get
> 5. I executed mix deps.compile
> 6. I executed mix ecto.create

Did you try running the `mix ecto.create` command inside of the individual `ib_gib` and `web_gib` folders? I would start with just the `ib_gib` project, since it does not depend on anything else. `web_gib`, however, depends on `ib_gib`, as `web_gib` is the phoenix web layer very much like the recent Phoenix `MyApp.Web` namespacing convention (I love their changes FTMP). And so it might be easier just to get a single one going first, and I'm unsure if I've ever tried to run them from the root umbrella folder. 

> Of course I tried it and I got same error.

By "tried it", do you mean that you put the port back in the configuration? I'm not trying to nitpick or anything, just trying to be explicit. Remote troubleshooting is tough! :sweat_smile:

**Comment by Eiji7** [comment]
@bill-mybiz: ah, yes my bad
I corrected it and I see error that you posted on forum.
I will look at it.

**Comment by bill-mybiz** [comment]
I've just set up another machine and I'm able to reproduce what looks to be the same `DBConnection` error. Let me see if I can get it to work on this machine, then I'll let you know.

**Comment by bill-mybiz** [comment]
@Eiji7 Ok, I feel silly. I had it up and going with `mix ecto.create/migrate/reset` but couldn't get the tests going. Then I realized that I have another configuration for tests in `test.exs`. I think I had that in the back of my mind the whole time! Anyway, change both `test.exs` to use localhost as well, and see if that does it for you. 

Also, if you hadn't already had postgres installed, you may have to set up the postgres user role.

**Comment by Eiji7** [comment]
@bill-mybiz: I know - it's already ~working - as I said: I have same error that you posted on forum
I don't saw this error before, so I need to look at whole code.
I have first question:
In `&IbGib.Data.Schemas.Seeds.insert/2` you are calling `&Repo.insert/2` in `try/rescue` block. The part I don't understand is why you are using `try/rescue`? From [docs](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2) it does not raise any error - only `insert!` function does it.

**Comment by bill-mybiz** [comment]
> In &IbGib.Data.Schemas.Seeds.insert/2 you are calling &Repo.insert/2 in try/rescue block. The part I don't understand is why you are using try/rescue? From docs it does not raise any error - only insert! function does it.

Oh gosh, probably just being overly cautious. Sometimes I do that. _Possibly_ in this case, it is during the migration part of code, and so the reasoning might be that I want to be _absolutely sure_ that there are no unhandled exceptions thrown. And since I don't own the `insert` code, I can't vouch for its integrity, even if they are using the `insert!` convention. Nothing personal against them, I'm just very cautious sometimes.

(_Or maybe_ I was just having a tough day and I had it in place as such and it wasn't worth the effort to remove afterwards or it didn't occur to me! But I'll go with the first one, since that sounds reasonable, because this is code outside of the supervisor structure. :sweat_smile:)

However, you should note that if you do a search for `rescue` in the application, you'll find there are only 4 instances of its use, and two of those are in `seeds.ex`. One of the other two is going away (as I'm moving away from code in the controller) and the commanding one is handling incoming commands and requires a response no matter what (i.e. don't fail fast).

**Comment by Eiji7** [comment]
@bill-mybiz: I found it!
Please comment/remove alias in file: `ib_gib_umb/apps/ib_gib/mix.exs`.

**Comment by bill-mybiz** [comment]
@Eiji7 That's awesome :exclamation: 

That's a very interesting bug! I believe I did that before there was a sandboxing feature for tests, and so now I would think it quite unnecessary.

Thanks for your perseverance and the help! :smiley: :champagne:

**Comment by bill-mybiz** [comment]
@Eiji7 Did you want to do a PR or do you want me to handle it?

**Comment by Eiji7** [comment]
@bill-mybiz: I don't know how you want to alias it, so I will let it to you 😄
